In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')
import os
pasta_drive = '/content/drive/My Drive/DadosAntaq/2024_2025/'
if os.path.exists(pasta_drive):
    arquivos = os.listdir(pasta_drive)
    print(f"Arquivos encontrados em '2024_2025': {arquivos}")
else:
    print(f"A pasta '2024_2025' não foi encontrada no Google Drive.")

Mounted at /content/drive
Arquivos encontrados em '2024_2025': ['2024Atracacao.csv', '2024Carga.csv', '2024TemposAtracacao.csv', '2024TemposAtracacaoParalisacao.csv', '2025Atracacao.csv', '2025Carga.csv', '2025TemposAtracacao.csv', '2025TemposAtracacaoParalisacao.csv']

In [3]:
arquivo_1 = '/content/drive/My Drive/DadosAntaq/2024_2025/2024Atracacao.csv'
arquivo_2 = '/content/drive/My Drive/DadosAntaq/2024_2025/2024Carga.csv'
arquivo_3 = '/content/drive/My Drive/DadosAntaq/2024_2025/2024TemposAtracacaoParalisacao.csv'
arquivo_4 = '/content/drive/My Drive/DadosAntaq/2024_2025/2025Atracacao.csv'
arquivo_5 = '/content/drive/My Drive/DadosAntaq/2024_2025/2025Carga.csv'
arquivo_6 = '/content/drive/My Drive/DadosAntaq/2024_2025/2025TemposAtracacaoParalisacao.csv'

In [4]:
Atracacao24 = pd.read_csv(arquivo_1, sep=';', encoding='utf-8', low_memory=False)
Carga24 = pd.read_csv(arquivo_2, sep=';', encoding='utf-8', low_memory=False)
TemposParalisacao24 = pd.read_csv(arquivo_3, sep=';', encoding='utf-8', low_memory=False)
Atracacao25 = pd.read_csv(arquivo_4, sep=';', encoding='utf-8', low_memory=False)
Carga25 = pd.read_csv(arquivo_5, sep=';', encoding='utf-8', low_memory=False)
TemposParalisacao25 = pd.read_csv(arquivo_6, sep=';', encoding='utf-8', low_memory=False)

In [14]:
Atracacao24_25 = pd.concat([Atracacao24, Atracacao25], ignore_index=True)
Carga24_25 = pd.concat([Carga24, Carga25], ignore_index=True)
TemposParalisacao24_25 = pd.concat([TemposParalisacao24, TemposParalisacao25], ignore_index=True)

In [15]:
Atracacao24_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223056 entries, 0 to 223055
Data columns (total 29 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   IDAtracacao                     223056 non-null  int64
 1   CDTUP                           223056 non-null  object
 2   IDBerco                         222952 non-null  object
 3   Berço                           222951 non-null  object
 4   Porto Atracação                 222952 non-null  object
 5   Coordenadas                     222952 non-null  object
 6   Apelido Instalação Portuária    66263 non-null   object
 7   Complexo Portuário              223056 non-null  object
 8   Tipo da Autoridade Portuária    223056 non-null  object
 9   Data Atracação                  222952 non-null  object
 10  Data Chegada                    222952 non-null  object
 11  Data Desatracação               223056 non-null  object
 12  Data Início Operação            208384 non-null  object
 13  Data Término Operação           208387 non-null  object
 14  Ano                             223056 non-null  int64
 15  Mes                             223056 non-null  object
 16  Tipo de Operação                222952 non-null  object
 17  Tipo de Navegação da Atracação  222952 non-null  object
 18  Nacionalidade do Armador        222952 non-null  float64
 19  FlagMCOperacaoAtracacao         223056 non-null  int64
 20  Terminal                        222951 non-null  object
 21  Município                       222951 non-null  object
 22  UF                              222951 non-null  object
 23  SGUF                            222951 non-null  object
 24  Região Geográfica               222951 non-null  object
 25  Região Hidrográfica             98528 non-null   object
 26  Instalação Portuária em Rio     223056 non-null  object
 27  Nº da Capitania                 143644 non-null  object
 28  Nº do IMO                       113913 non-null  float64
dtypes: float64(2), int64(3), object(24)
memory usage: 49.4+ MB

In [22]:
Atracacao24_25.head(10)

,IDAtracacao,CDTUP,IDBerco,Berço,Porto Atracação,Coordenadas,Apelido Instalação Portuária,Complexo Portuário,Tipo da Autoridade Portuária,Data Atracação,...,FlagMCOperacaoAtracacao,Terminal,Município,UF,SGUF,Região Geográfica,Região Hidrográfica,Instalação Portuária em Rio,Nº da Capitania,Nº do IMO
0,1513682,BRSSZ,SSZ0627,OUTEIRINHOS 2 + OUTEIRINHOS 1,SANTOS,"-46.301939,-23.966053",NaN,SANTOS,Porto Organizado,2024-11-14 09:50:00,...,1,CAIS DO OUTEIRINHOS - PÚBLICO,SANTOS,SÃO PAULO,SP,SUDESTE,NaN,Não,NaN,NaN
1,1474172,BRSSZ,SSZ0525,ARM FRIG/25,SANTOS,"-46.301939,-23.966053",NaN,SANTOS,Porto Organizado,2024-07-26 09:50:00,...,1,CAIS DO OUTEIRINHOS - PÚBLICO,SANTOS,SÃO PAULO,SP,SUDESTE,NaN,Não,NaN,NaN
2,1435902,BRREC,RECA-07,RECA-07,RECIFE,"-34.868332,-8.053888000000001",Arrecife dos Navios,SUAPE - RECIFE,Porto Organizado,2024-03-21 09:20:00,...,1,CAIS PÚBLICO,RECIFE,PERNAMBUCO,PE,NORDESTE,NaN,Não,NaN,NaN
3,1474171,BRSSZ,SSZ0627,OUTEIRINHOS 2 + OUTEIRINHOS 1,SANTOS,"-46.301939,-23.966053",NaN,SANTOS,Porto Organizado,2024-07-26 09:40:00,...,1,CAIS DO OUTEIRINHOS - PÚBLICO,SANTOS,SÃO PAULO,SP,SUDESTE,NaN,Não,NaN,NaN
4,1474173,BRSSZ,SSZ0525,ARM FRIG/25,SANTOS,"-46.301939,-23.966053",NaN,SANTOS,Porto Organizado,2024-07-25 13:50:00,...,1,CAIS DO OUTEIRINHOS - PÚBLICO,SANTOS,SÃO PAULO,SP,SUDESTE,NaN,Não,NaN,NaN
5,1427802,BRVIX,VIX0102,102,VITÓRIA,"-40.339444,-20.3225",NaN,VITÓRIA,Porto Organizado,2024-01-25 10:00:00,...,1,CAIS COMERCIAL,VITÓRIA,ESPÍRITO SANTO,ES,SUDESTE,NaN,Não,NaN,NaN
6,1453599,BRMCZ,MCZ0002,Berço 2,MACEIÓ,"-35.726388,-9.683056000000001",NaN,MACEIÓ,Porto Organizado,2024-05-10 09:50:00,...,1,CAIS DO AA-01,MACEIÓ,ALAGOAS,AL,NORDESTE,NaN,Não,NaN,NaN
7,1433331,BRMCZ,MCZ0002,Berço 2,MACEIÓ,"-35.726388,-9.683056000000001",NaN,MACEIÓ,Porto Organizado,2024-03-08 07:45:00,...,1,CAIS DO AA-01,MACEIÓ,ALAGOAS,AL,NORDESTE,NaN,Não,NaN,NaN
8,1453598,BRMCZ,MCZ0002,Berço 2,MACEIÓ,"-35.726388,-9.683056000000001",NaN,MACEIÓ,Porto Organizado,2024-05-09 15:40:00,...,1,CAIS DO AA-01,MACEIÓ,ALAGOAS,AL,NORDESTE,NaN,Não,NaN,NaN
9,1433333,BRMCZ,MCZ0002,Berço 2,MACEIÓ,"-35.726388,-9.683056000000001",NaN,MACEIÓ,Porto Organizado,2024-03-15 09:00:00,...,1,CAIS DO AA-01,MACEIÓ,ALAGOAS,AL,NORDESTE,NaN,Não,NaN,NaN

In [17]:
cols_datas = [
    "Data Atracação", "Data Chegada", "Data Desatracação",
    "Data Início Operação", "Data Término Operação"
]

for col in cols_datas:
    Atracacao24_25[col] = pd.to_datetime(Atracacao24_25[col], errors="coerce", dayfirst=True)

In [21]:
cols_texto = [
    "Porto Atracação", "Complexo Portuário", "Terminal",
    "Município", "UF", "Região Geográfica"
]

for col in cols_texto:
    Atracacao24_25[col] = Atracacao24_25[col].str.strip().str.upper()

In [23]:
Carga24_25 = pd.concat([Carga24, Carga25], ignore_index=True)

In [29]:
Carga24_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4905266 entries, 0 to 4905265
Data columns (total 27 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   IDCarga                                 int64
 1   IDAtracacao                             int64
 2   Origem                                  object
 3   Destino                                 object
 4   CDMercadoria                            object
 5   Tipo Operação da Carga                  object
 6   Carga Geral Acondicionamento            object
 7   ConteinerEstado                         object
 8   Tipo Navegação                          object
 9   FlagAutorizacao                         object
 10  FlagCabotagem                           float64
 11  FlagCabotagemMovimentacao               float64
 12  FlagConteinerTamanho                    object
 13  FlagLongoCurso                          float64
 14  FlagMCOperacaoCarga                     int64
 15  FlagOffshore                            float64
 16  FlagTransporteViaInterioir              int64
 17  Percurso Transporte em vias Interiores  object
 18  Percurso Transporte Interiores          object
 19  STNaturezaCarga                         object
 20  STSH2                                   object
 21  STSH4                                   object
 22  Natureza da Carga                       object
 23  Sentido                                 object
 24  TEU                                     object
 25  QTCarga                                 int64
 26  VLPesoCargaBruta                        float64
dtypes: float64(5), int64(5), object(17)
memory usage: 1010.5+ MB

In [33]:
Carga24_25.head(10)

,IDCarga,IDAtracacao,Origem,Destino,CDMercadoria,Tipo Operação da Carga,Carga Geral Acondicionamento,ConteinerEstado,Tipo Navegação,FlagAutorizacao,...,Percurso Transporte em vias Interiores,Percurso Transporte Interiores,STNaturezaCarga,STSH2,STSH4,Natureza da Carga,Sentido,TEU,QTCarga,VLPesoCargaBruta
0,35449975,1404798,BRVDC,BRVDC,CA01,APOIO,SOLTA,NaN,APOIO PORTUÁRIO,S,...,NaN,NaN,Compartilhado,Compartilhado,Compartilhado,CARGA GERAL,EMBARCADOS,0.0,90,3.98
1,35449976,1404798,BRVDC,RULED,2201,LONGO CURSO EXPORTAÇÃO,NaN,NaN,LONGO CURSO,S,...,NaN,Longo Curso em vias interiores,Compartilhado,Compartilhado,Compartilhado,GRANEL LÍQUIDO E GASOSO,EMBARCADOS,0.0,0,17.66
2,35449977,1404798,BRVDC,CAPAF,2818,LONGO CURSO EXPORTAÇÃO,NaN,NaN,LONGO CURSO,S,...,NaN,Longo Curso em vias interiores,Compartilhado,Compartilhado,Compartilhado,GRANEL SÓLIDO,EMBARCADOS,0.0,0,34452.28
3,35449978,1404801,BRES002,BRIGI,2601,CABOTAGEM,NaN,NaN,CABOTAGEM,S,...,NaN,NaN,Exclusivo,Exclusivo,Exclusivo,GRANEL SÓLIDO,EMBARCADOS,0.0,0,60499.00
4,35450024,1404849,USMOB,BRRJ016,2701,LONGO CURSO IMPORTAÇÃO,NaN,NaN,LONGO CURSO,S,...,NaN,NaN,Exclusivo,Exclusivo,Exclusivo,GRANEL SÓLIDO,DESEMBARCADOS,0.0,0,72273.00
5,35450146,1404937,BRVDC,BRVDC,CA01,APOIO,SOLTA,NaN,APOIO PORTUÁRIO,S,...,NaN,NaN,Exclusivo,Compartilhado,Compartilhado,CARGA GERAL,EMBARCADOS,0.0,23,1.92
6,35450147,1404937,BRVDC,BRVDC,CA01,APOIO,SOLTA,NaN,APOIO PORTUÁRIO,S,...,NaN,NaN,Exclusivo,Compartilhado,Compartilhado,CARGA GERAL,EMBARCADOS,0.0,20,4.68
7,35450148,1404937,BRVDC,BRVDC,CA01,APOIO,SOLTA,NaN,APOIO PORTUÁRIO,S,...,NaN,NaN,Exclusivo,Compartilhado,Compartilhado,CARGA GERAL,DESEMBARCADOS,0.0,1,0.68
8,35450149,1404937,BRVDC,IQUQR,1213,LONGO CURSO EXPORTAÇÃO,SOLTA,NaN,LONGO CURSO,S,...,NaN,Longo Curso em vias interiores,Exclusivo,Compartilhado,Compartilhado,CARGA GERAL,EMBARCADOS,0.0,7500,161.04
9,35450150,1404937,BRVDC,IQUQR,0102,LONGO CURSO EXPORTAÇÃO,SOLTA,NaN,LONGO CURSO,S,...,NaN,Longo Curso em vias interiores,Exclusivo,Compartilhado,Compartilhado,CARGA GERAL,EMBARCADOS,0.0,8000,2964.12

In [25]:
cols_texto = [
    "Origem", "Destino", "Tipo Operação da Carga",
    "Carga Geral Acondicionamento", "Tipo Navegação",
    "Natureza da Carga", "Sentido"
]

for col in cols_texto:
    Carga24_25[col] = Carga24_25[col].str.strip().str.upper()

In [27]:
Carga24_25["VLPesoCargaBruta"] = pd.to_numeric(
    Carga24_25["VLPesoCargaBruta"].str.replace(",", ".", regex=False),
    errors="coerce"
)

In [28]:
Carga24_25["VLPesoCargaBruta"].isna().sum()

np.int64(0)

In [30]:
Carga24_25["TEU"] = pd.to_numeric(
    Carga24_25["TEU"].str.replace(",", ".", regex=False),
    errors="coerce"
)

cols_flags = [
    "FlagCabotagem", "FlagCabotagemMovimentacao",
    "FlagLongoCurso", "FlagOffshore"
]

for col in cols_flags:
    Carga24_25[col] = Carga24_25[col].astype("Int64")

In [34]:
Carga24_25["IDCarga"].duplicated().sum()

np.int64(0)

In [42]:
TemposParalisacao24_25 = pd.concat([TemposParalisacao24, TemposParalisacao25], ignore_index=True)

In [43]:
TemposParalisacao24_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453116 entries, 0 to 453115
Data columns (total 5 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   IDTemposDescontos       453116 non-null  int64
 1   IDAtracacao             453116 non-null  int64
 2   DescricaoTempoDesconto  453116 non-null  object
 3   DTInicio                453116 non-null  object
 4   DTTermino               453116 non-null  object
dtypes: int64(2), object(3)
memory usage: 17.3+ MB

In [55]:
TemposParalisacao24_25.tail(10)

,IDTemposDescontos,IDAtracacao,DescricaoTempoDesconto,DTInicio,DTTermino,Duracao,Duracao_horas
453106,1470735,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-03 19:00:00,2025-10-03 19:30:00,0 days 00:30:00,0.50
453107,1470736,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-04 00:40:00,2025-10-04 01:00:00,0 days 00:20:00,0.33
453108,1470737,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-04 01:00:00,2025-10-04 01:20:00,0 days 00:20:00,0.33
453109,1470738,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-04 03:50:00,2025-10-04 04:20:00,0 days 00:30:00,0.50
453110,1470739,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-04 07:00:00,2025-10-04 09:00:00,0 days 02:00:00,2.00
453111,1470740,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-04 10:35:00,2025-10-04 11:00:00,0 days 00:25:00,0.42
453112,1470741,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-02 19:00:00,2025-10-02 19:30:00,0 days 00:30:00,0.50
453113,1470742,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-03 00:40:00,2025-10-03 01:00:00,0 days 00:20:00,0.33
453114,1470743,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-03 01:00:00,2025-10-03 01:20:00,0 days 00:20:00,0.33
453115,1470744,1624462,SEM OPERAÇÃO POR CONVENIÊNCIA DO AGENTE,2025-10-02 13:00:00,2025-10-02 13:20:00,0 days 00:20:00,0.33

In [45]:
for col in ["DTInicio", "DTTermino"]:
    TemposParalisacao24_25[col] = pd.to_datetime(
        TemposParalisacao24_25[col],
        errors="coerce"
    )

In [49]:
TemposParalisacao24_25["Duracao"] = (
    TemposParalisacao24_25["DTTermino"] - TemposParalisacao24_25["DTInicio"]
)
TemposParalisacao24_25["Duracao_horas"] = (
    TemposParalisacao24_25["Duracao"].dt.total_seconds() / 3600
)

In [51]:
TemposParalisacao24_25["DescricaoTempoDesconto"] = (
    TemposParalisacao24_25["DescricaoTempoDesconto"]
    .str.strip()
    .str.upper()
)

In [53]:
TemposParalisacao24_25[TemposParalisacao24_25["Duracao_horas"] < 0]

Empty DataFrame
Columns: [IDTemposDescontos, IDAtracacao, DescricaoTempoDesconto, DTInicio, DTTermino, Duracao, Duracao_horas]
Index: []

In [54]:
TemposParalisacao24_25["Duracao_horas"] = TemposParalisacao24_25["Duracao_horas"].round(2)

In [56]:
Atracacao24_25.to_csv("Atracacao2024_2025.csv", index=False, sep=";", encoding="utf-8")
Carga24_25.to_csv("Carga2024_2025.csv", index=False, sep=";", encoding="utf-8")
TemposParalisacao24_25.to_csv("TemposParalisacao2024_2025.csv", index=False, sep=";", encoding="utf-8")

In [57]:
from google.colab import drive
drive.mount('/content/drive')

Atracacao24_25.to_csv("/content/drive/MyDrive/DadosAntaq/Atracacao2024_2025.csv", index=False, sep=";", encoding="utf-8")
Carga24_25.to_csv("/content/drive/MyDrive/DadosAntaq/Carga2024_2025.csv", index=False, sep=";", encoding="utf-8")
TemposParalisacao24_25.to_csv("/content/drive/MyDrive/DadosAntaq/TemposParalisacao2024_2025.csv", index=False, sep=";", encoding="utf-8")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).